export enum ReypaymentRouterError {
    DEBT_AGREEMENT_NONEXISTENT,
    PAYER_BALANCE_OR_ALLOWANCE_INSUFFICIENT,
    PAYER_OWNERSHIP_OR_ROUTER_APPROVAL_MISSING,
    ROUTER_UNAUTHORIZED_TO_REPORT_REPAYMENT,
}
