// Generated by mnemonic "arm impose enemy alpha bird attend hunt host town sleep charge catalog"
export interface Account {
    address: string;
    privateKey: string;
}
const NULL_ADDRESS = "0x0000000000000000000000000000000000000000";

const ACCOUNTS: Account[] = [
    {
        address: "0xd2f45e02ab7b190ac9a87b743eab4c8f2ed0e491",
        privateKey: "a0953ce99c51b184d61af5103a64f7e11694f6f27f23796a173a5105af143b50",
    },
    {
        address: "0x3fa17c1f1a0ae2db269f0b572ca44b15bc83929a",
        privateKey: "74e82351f83f2a4ac383a1fd0e1e8abd6e49837f2a704d4d26f74f9e9c7ea1b0",
    },
    {
        address: "0x6385d458c76cd5360041245daa04df8f50d11a82",
        privateKey: "d888879eb7da10faf7270601d1f61cea4b26df935e013db4bbc55eaab11d6eaf",
    },
    {
        address: "0xbb90d6ca4e454be5f049d79322b3a52100383d02",
        privateKey: "138c80445039171892e53ef3934e771e252ef898b308b3b137e17b589a91ada7",
    },
    {
        address: "0xdc4845b45c6c08f4ce4a8ef5e0493d8bf6158da0",
        privateKey: "c0c78e8f4b88521628318e86c0d4ed314444e3c404060e662a406577e1a883d6",
    },
    {
        address: "0x690a4ad7d771ff1822d7757150cb446e114b8d74",
        privateKey: "530ed0d6491668ade0630b88cd720f8b96cc75e768d834248538eaf22d097631",
    },
    {
        address: "0xbe0f946d1b202cfda86418bbe7173dc60dea52ff",
        privateKey: "0d3d64770d836a2c0cec8eeac696340b1c3778dd77a10783f7ad1c53a8f3e04e",
    },
    {
        address: "0x46243fb9133dd07cd9a78330893a18d4c9cf2a2a",
        privateKey: "29752cb960df2dbdf40fd41a821e5a28a6cec139f2ebaa6b94cc6de39bb8c80b",
    },
    {
        address: "0x8d4f214a98765f1cb7faebbed490032b314eeb05",
        privateKey: "5bd0cb7f4f3ffe4c51000f8164575a414119fb7b867de5d9a871ed4a815a779f",
    },
    {
        address: "0x1af81f826e7422981a9783612065d8498848b274",
        privateKey: "4036f63871582f7884c996fd1fc1222ba55552ca5f3f159682ae535ba7c77f2e",
    },
];

export { ACCOUNTS, NULL_ADDRESS };
